//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BabyApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BabyApp.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anteater.
        /// </summary>
        public static string Anteater {
            get {
                return ResourceManager.GetString("Anteater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antelope.
        /// </summary>
        public static string Antelope {
            get {
                return ResourceManager.GetString("Antelope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baby Misc.
        /// </summary>
        public static string AppBarBabyMiscButton {
            get {
                return ResourceManager.GetString("AppBarBabyMiscButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY APPLICATION.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badger.
        /// </summary>
        public static string Badger {
            get {
                return ResourceManager.GetString("Badger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bear.
        /// </summary>
        public static string Bear {
            get {
                return ResourceManager.GetString("Bear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Butterfly.
        /// </summary>
        public static string Butterfly {
            get {
                return ResourceManager.GetString("Butterfly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capuchinmonkey.
        /// </summary>
        public static string Capuchinmonkey {
            get {
                return ResourceManager.GetString("Capuchinmonkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caribou.
        /// </summary>
        public static string Caribou {
            get {
                return ResourceManager.GetString("Caribou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chameleon.
        /// </summary>
        public static string Chameleon {
            get {
                return ResourceManager.GetString("Chameleon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheetah.
        /// </summary>
        public static string Cheetah {
            get {
                return ResourceManager.GetString("Cheetah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cow.
        /// </summary>
        public static string Cow {
            get {
                return ResourceManager.GetString("Cow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crab.
        /// </summary>
        public static string Crab {
            get {
                return ResourceManager.GetString("Crab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dog.
        /// </summary>
        public static string Dog {
            get {
                return ResourceManager.GetString("Dog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dolphin.
        /// </summary>
        public static string Dolphin {
            get {
                return ResourceManager.GetString("Dolphin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DragonFly.
        /// </summary>
        public static string DragonFly {
            get {
                return ResourceManager.GetString("DragonFly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duck.
        /// </summary>
        public static string Duck {
            get {
                return ResourceManager.GetString("Duck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eagle.
        /// </summary>
        public static string Eagle {
            get {
                return ResourceManager.GetString("Eagle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elephant.
        /// </summary>
        public static string Elephant {
            get {
                return ResourceManager.GetString("Elephant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elk.
        /// </summary>
        public static string Elk {
            get {
                return ResourceManager.GetString("Elk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fish.
        /// </summary>
        public static string Fish {
            get {
                return ResourceManager.GetString("Fish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fox.
        /// </summary>
        public static string Fox {
            get {
                return ResourceManager.GetString("Fox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giraffe.
        /// </summary>
        public static string Giraffe {
            get {
                return ResourceManager.GetString("Giraffe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guineapig.
        /// </summary>
        public static string Guineapig {
            get {
                return ResourceManager.GetString("Guineapig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hippopotamus.
        /// </summary>
        public static string Hippopotamus {
            get {
                return ResourceManager.GetString("Hippopotamus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horse.
        /// </summary>
        public static string Horse {
            get {
                return ResourceManager.GetString("Horse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iguana.
        /// </summary>
        public static string Iguana {
            get {
                return ResourceManager.GetString("Iguana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jaguar.
        /// </summary>
        public static string Jaguar {
            get {
                return ResourceManager.GetString("Jaguar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kangaroo.
        /// </summary>
        public static string Kangaroo {
            get {
                return ResourceManager.GetString("Kangaroo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kitten.
        /// </summary>
        public static string Kitten {
            get {
                return ResourceManager.GetString("Kitten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koala.
        /// </summary>
        public static string Koala {
            get {
                return ResourceManager.GetString("Koala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lemur.
        /// </summary>
        public static string Lemur {
            get {
                return ResourceManager.GetString("Lemur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lion.
        /// </summary>
        public static string Lion {
            get {
                return ResourceManager.GetString("Lion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macaw.
        /// </summary>
        public static string Macaw {
            get {
                return ResourceManager.GetString("Macaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marmot.
        /// </summary>
        public static string Marmot {
            get {
                return ResourceManager.GetString("Marmot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monkey.
        /// </summary>
        public static string Monkey {
            get {
                return ResourceManager.GetString("Monkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocelot.
        /// </summary>
        public static string Ocelot {
            get {
                return ResourceManager.GetString("Ocelot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Octopus.
        /// </summary>
        public static string Octopus {
            get {
                return ResourceManager.GetString("Octopus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orca.
        /// </summary>
        public static string Orca {
            get {
                return ResourceManager.GetString("Orca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otter.
        /// </summary>
        public static string Otter {
            get {
                return ResourceManager.GetString("Otter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owl.
        /// </summary>
        public static string Owl {
            get {
                return ResourceManager.GetString("Owl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panda.
        /// </summary>
        public static string Panda {
            get {
                return ResourceManager.GetString("Panda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Penguin.
        /// </summary>
        public static string Penguin {
            get {
                return ResourceManager.GetString("Penguin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pig.
        /// </summary>
        public static string Pig {
            get {
                return ResourceManager.GetString("Pig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prayingmantis.
        /// </summary>
        public static string Prayingmantis {
            get {
                return ResourceManager.GetString("Prayingmantis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rabbit.
        /// </summary>
        public static string Rabbit {
            get {
                return ResourceManager.GetString("Rabbit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Racoon.
        /// </summary>
        public static string Racoon {
            get {
                return ResourceManager.GetString("Racoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redfox.
        /// </summary>
        public static string Redfox {
            get {
                return ResourceManager.GetString("Redfox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redpanda.
        /// </summary>
        public static string Redpanda {
            get {
                return ResourceManager.GetString("Redpanda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rhino.
        /// </summary>
        public static string Rhino {
            get {
                return ResourceManager.GetString("Rhino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shark.
        /// </summary>
        public static string Shark {
            get {
                return ResourceManager.GetString("Shark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheep.
        /// </summary>
        public static string Sheep {
            get {
                return ResourceManager.GetString("Sheep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skink.
        /// </summary>
        public static string Skink {
            get {
                return ResourceManager.GetString("Skink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snake.
        /// </summary>
        public static string Snake {
            get {
                return ResourceManager.GetString("Snake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snowleopard.
        /// </summary>
        public static string Snowleopard {
            get {
                return ResourceManager.GetString("Snowleopard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Squid.
        /// </summary>
        public static string Squid {
            get {
                return ResourceManager.GetString("Squid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Squirrel.
        /// </summary>
        public static string Squirrel {
            get {
                return ResourceManager.GetString("Squirrel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starfish.
        /// </summary>
        public static string Starfish {
            get {
                return ResourceManager.GetString("Starfish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sumatrantiger.
        /// </summary>
        public static string Sumatrantiger {
            get {
                return ResourceManager.GetString("Sumatrantiger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tayra.
        /// </summary>
        public static string Tayra {
            get {
                return ResourceManager.GetString("Tayra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiger.
        /// </summary>
        public static string Tiger {
            get {
                return ResourceManager.GetString("Tiger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tortoise.
        /// </summary>
        public static string Tortoise {
            get {
                return ResourceManager.GetString("Tortoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walrus.
        /// </summary>
        public static string Walrus {
            get {
                return ResourceManager.GetString("Walrus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wolf.
        /// </summary>
        public static string Wolf {
            get {
                return ResourceManager.GetString("Wolf", resourceCulture);
            }
        }
    }
}
