//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BabyApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BabyApp.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anteater.
        /// </summary>
        public static string Anteater {
            get {
                return ResourceManager.GetString("Anteater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antelope.
        /// </summary>
        public static string Antelope {
            get {
                return ResourceManager.GetString("Antelope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baby Misc.
        /// </summary>
        public static string AppBarBabyMiscButton {
            get {
                return ResourceManager.GetString("AppBarBabyMiscButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY APPLICATION.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badger.
        /// </summary>
        public static string Badger {
            get {
                return ResourceManager.GetString("Badger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bear.
        /// </summary>
        public static string Bear {
            get {
                return ResourceManager.GetString("Bear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Butterfly.
        /// </summary>
        public static string Butterfly {
            get {
                return ResourceManager.GetString("Butterfly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capuchinmonkey.
        /// </summary>
        public static string Capuchinmonkey {
            get {
                return ResourceManager.GetString("Capuchinmonkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caribou.
        /// </summary>
        public static string Caribou {
            get {
                return ResourceManager.GetString("Caribou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chameleon.
        /// </summary>
        public static string Chameleon {
            get {
                return ResourceManager.GetString("Chameleon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheetah.
        /// </summary>
        public static string Cheetah {
            get {
                return ResourceManager.GetString("Cheetah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cow.
        /// </summary>
        public static string Cow {
            get {
                return ResourceManager.GetString("Cow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crab.
        /// </summary>
        public static string Crab {
            get {
                return ResourceManager.GetString("Crab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dog.
        /// </summary>
        public static string Dog {
            get {
                return ResourceManager.GetString("Dog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duck.
        /// </summary>
        public static string Duck {
            get {
                return ResourceManager.GetString("Duck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elephant.
        /// </summary>
        public static string Elephant {
            get {
                return ResourceManager.GetString("Elephant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lion.
        /// </summary>
        public static string Lion {
            get {
                return ResourceManager.GetString("Lion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pig.
        /// </summary>
        public static string Pig {
            get {
                return ResourceManager.GetString("Pig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
    }
}
